# Generated by Django 5.1.2 on 2024-10-26 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_remove_user_username_user_groups_user_user_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_name",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
