# Generated by Django 5.1.2 on 2024-10-26 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_alter_user_user_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="user_name",
            new_name="username",
        ),
    ]
